### ISSUE TITLE
Peer to peer code review (group)

### ISSUE THREAD

**Issue by zhorabay** [zhorabay/My-portfolio#11]
Here morning session team of week 4 module 1 gave comments:

**Comment by evansnyamekye** [comment]
REQUIRED CHANGES ♻️ 
-- Good design and good use of HTML semantic tags. 
--Good implementation of CSS Properties. 
--Kindly check your width of mobile display and correct it, its overlapping 

Thank you 😀.

**Comment by ayaderaghul** [comment]
Hi, please add some images to your work cards in the work section. It helps the UI of the page since it gives more information on the projects.

![image](https://github.com/zhorabay/My-portfolio/assets/7457301/edbbef00-a8d2-4c17-9f71-d0815d4c130c)
