### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by zhorabay** [zhorabay/My-portfolio#7]

**Comment by lucy-sees** [comment]
## Hi @zhorabay , 

Your project is looking great!   
Congratulations! 🎉 

## To Highlight
- Descriptive commit messages ✔️ 
- Professional looking README file✔️ 
- Good overall design ✔️ 
![7E2e](https://github.com/George7h/George7h.github.io/assets/100368317/b9bc4d59-205a-452c-8d08-72765e327494)

Cheers and Happy coding!👏👏👏

**Comment by zhorabay** [comment]
Thank you for your review! I appreciate it!
